IDservice/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from IDservice import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import  url
from accounts import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns=[
    url(r'^login/$', login, { 'template_name': 'accounts/login.html' }, name='login'),
    url(r'^logout/$', logout, { 'template_name': 'accounts/logout.html'}, name='logout'),
    ##url(r'^register/$', views.register, name='register'),  ##uncomment it to get back to old.
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^change-password$', views.change_password, name='change_passwords'),

    url(r'^reset-password/$', password_reset, { 'template_name': 'accounts/reset_password.html', 'post_reset_redirect':'accounts:password_reset_done',
    'email_template_name':'accounts/reset_password_email.html' }, name='reset_password'),

    url(r'^reset_password/done$', password_reset_done, {'template_name':'accounts/reset-password_reset_done'}, name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name':'accounts/reset-password_reset_confirm.html',
        'post_reset_redirect':'password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete, {'template_name':'accounts/reset-password_reset_complete.html'}, name='password_reset_complete'),

    url(r'^password/$', views.change_password),

    ##
    url(r'^register/$', views.SignUpView.as_view(), name='register'),
    url(r'^register/student/$', views.register, name='student_register'),
    url(r'^register/teacher/$', views.Teacherregister, name='teacher_register'),
    url(r'^register/HOD/$', views.hodregister, name='hod_register'),
    ## remove all if you want to go back to old
]

home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views

urlpatterns=[
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_students, name='change_students'),
    url(r'^send_mail_to_fa$', views.send_mail_to_fa, name='send_mail_to_fa'),           ##remove to get the old back.
    url(r'^bonafied-certificate$', views.upload_bonafied_form, name='upload_bonafied_form'),
    url(r'^Internship$', views.Internship, name='Internship'),
    url(r'^Internship/upload$', views.upload_internship_form, name='upload_internship_form'),
    url(r'^onlyforhod$', views.onlyforhod_view, name='onlyforhod'),
    #url(r'^Retest$', views.Retest, name='Retest'),
    url(r'^Retest/upload$', views.upload_retest_form, name='upload_retest_form'),
    url(r'^Retest/retest_list$', views.retest_list, name='retest_list'),
    url(r'^Retest/accepted_students_list$', views.accepted_students_view, name='accepted_students'),
    url(r'^genetate_pdfs$', views.generate_pdfs_view, name='generate_pdfs'),
    url(r'^genetate_pdfs_actual$', views.generate_pdfs_actual, name='generate_pdfs_actual'),
    #url(r'^genetate_obj_pdf$', views.generate_obj_pdf, name='generate_obj_pdf')
]

home/models.py
from django.db import models
#from django.contrib.auth.models import AbstractUser  #import User to get back to previous way.
from accounts.models import User, Students  ##uncomment to get back to old
##this is of least importance.
#class Post(models.Model):
    #post = models.CharField(max_length=100)
    #user = models.ForeignKey(User)
    #created = models.DateTimeField(auto_now_add=True)
    #updated = models.DateTimeField(auto_now=True)
##can be removed.


##
#class FacultyAdvisor(model.Model):

##


class Student(models.Model):
    users = models.ManyToManyField(User)   #
    current_user = models.ForeignKey(User, related_name='owner', null=True)

    @classmethod
    def make_student(cls, current_user, new_student):
        student, created=cls.objects.get_or_create(
            current_user=current_user
        )
        student.users.add(new_student)


    @classmethod
    def loose_student(cls, current_user, new_student):
        student, created=cls.objects.get_or_create(
            current_user=current_user
        )
        student.users.remove(new_student)

#class FacultyAdvisor(models.Model):
#    users = models.OneToOneField(User)
#    users.user_type=2

class Bonafied(models.Model):
    proof = models.FileField(upload_to = "students/bonafied")
    name = models.CharField(max_length=100)
    register_number = models.CharField(max_length=100, null=True)
    purpose = models.CharField(max_length=200, null=True)
    Fa_name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


##
INTERNSHIP_CHOICES=[
    ('On Campus', 'On Campus'),
    ('Off Campus', 'Off Campus')
]
class Internship(models.Model):
    proof = models.FileField(upload_to = "students/Internship")
    name = models.CharField(max_length=100)
    register_number = models.CharField(max_length=100, null=True)
    type = models.CharField(max_length=100, choices=INTERNSHIP_CHOICES, null=True)
    Fa_name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name
##


##
TEST_CHOICES = [
    ('CT1', 'CT1'),
    ('CT2', 'CT2'),
    ('CT3', 'CT3'),
]

SUBJECT_CHOICES = [
    ('OS', 'OS'),
    ('CD', 'CD'),
    ('DS', 'DS'),
    ('DSD', 'DSD'),
]

class Retest(models.Model):
    proof = models.FileField(upload_to = "students/Retest")
    name = models.CharField(max_length=100)
    register_number = models.CharField(max_length=100, null=True)
    #test = models.CharField(max_length=50, null=True)
    #subject = models.CharField(max_length=100, null=True)
    subject = models.CharField(max_length=100, choices=SUBJECT_CHOICES, null= True)
    test = models.CharField(max_length=100, choices=TEST_CHOICES, null= True)
    Fa_name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name
##





##
class Accepted_students(models.Model):
    proof = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    register_number = models.CharField(max_length=100, null=True)
    type = models.CharField(max_length=100, null=True, blank=True)

    subject = models.CharField(max_length=100, null= True, blank=True)
    test = models.CharField(max_length=100, null= True, blank=True)
    purpose = models.CharField(max_length=200, null=True, blank=True)
    class Meta:
        unique_together = ["proof", "register_number", "type", "subject", "test", "purpose"]

    def __str__(self):
        return self.name
##




class FinalPDFgeneratedstudents(models.Model):
    proof = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    register_number = models.CharField(max_length=100, null=True)
    type = models.CharField(max_length=100, null=True, blank=True)

    subject = models.CharField(max_length=100, null= True, blank=True)
    test = models.CharField(max_length=100, null= True, blank=True)
    purpose = models.CharField(max_length=200, null=True, blank=True)
    class Meta:
        unique_together = ["proof", "name", "register_number", "type", "subject", "test", "purpose"]

    def __str__(self):
        return self.name






class YourModel(models.Model):
       proof = models.CharField(max_length=100, null=True)
       name = models.CharField(max_length=100, null=True)
       register_number = models.CharField(max_length=100, null=True)
       type = models.CharField(max_length=100, null=True, blank=True)

       subject = models.CharField(max_length=100, null= True, blank=True)
       test = models.CharField(max_length=100, null= True, blank=True)
       purpose = models.CharField(max_length=200, null=True, blank=True)
       pdf = models.FileField(upload_to='stuents/pdfs', null=True, blank=True)
       def __str__(self):
           return self.name

home/forms.py
from django import forms
from .models import Internship, Retest, Bonafied, Accepted_students, FinalPDFgeneratedstudents, YourModel
#from home.models import Post

class HomeForm(forms.ModelForm):
    pass

class BonafiedForm(forms.ModelForm):
    class Meta:
        model = Bonafied
        fields = ('name', 'register_number', 'purpose', 'Fa_name', 'proof')

class InternshipForm(forms.ModelForm):
    class Meta:
        model = Internship
        fields = ('name', 'register_number', 'type', 'Fa_name', 'proof')

class RetestForm(forms.ModelForm):
    class Meta:
        model = Retest
        fields = ('name', 'register_number', 'test', 'subject', 'Fa_name', 'proof')



#
class Accepted_studentsForm(forms.ModelForm):
    class Meta:
        model = Accepted_students
        fields='__all__'
        #field = ('name_a', 'register_number_a', 'test_a', 'type_a', 'subject_a', 'proof_a')

#

class FinalPDFgeneratedstudentsForm(forms.ModelForm):
    class Meta:
        model = FinalPDFgeneratedstudents
        fields = '__all__'


class YourModelForm(forms.ModelForm):
    class Meta:
        model = YourModel
        fields = '__all__'

home/templates/home/Internship.html
{% extends 'base.html' %}
{% block body %}
  <div class="container">
    <h2>For Internship</h2>
    <div class="col-md-3">
        <h1>Profile</h1>
        {% if user.userprofile.image %}
        <img src="{{ user.userprofile.image.url }}" width="140">
        {% endif %}
        <br>
        <p>Register Number: {{user}}</p>
        <p>First Name: {{user.first_name}}</p>
        <p>Last Name: {{user.last_name}}</p>
        <p>Email: {{user.email}}</p>
    </div>

    <div class="col-md-9">
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="file" name="document"><br>
          <button type="submit" name="button" class="btn btn-success">Upload File</button>
      </form>
      {% if url %}
        <p>Uploaded File: <a href="{{ url }}">{{ url }}</a></p>
      {% endif %}
    </div>
  </div>
{% endblock %}

home/templates/home/Retest1.html
{% extends 'base.html' %}
{% block body %}
  <div class="container">
    <h2>For bonafied</h2>
    <div class="col-md-3">
        <h1>Profile</h1>
        {% if user.userprofile.image %}
        <img src="{{ user.userprofile.image.url }}" width="140">
        {% endif %}
        <br>
        <p>Register Number: {{user}}</p>
        <p>First Name: {{user.first_name}}</p>
        <p>Last Name: {{user.last_name}}</p>
        <p>Email: {{user.email}}</p>
    </div>

    <div class="col-md-9">
      <table class='table'>
          <thead>
            <tr>
              <th>Type of Request: </th>
              <th>Name: </th>
              <th>Register Number: </th>
              <th>proof: </th>
              <th>Action: </th>
            </tr>
          </thead>
          <tbody>
            {% for retest in retests %}
             <!--{% if user.first_name == retest.Fa_name %}-->
              <tr>
                <td><h4>Restest</h4></td>
                <td>{{ retest.name }}</td>
                <td>{{ retest.register_number }}</td>
                <td>
                  <a href="{{ retest.proof.url }}" class="btn btn-success btn-sm" target='_blank'>Medical Proof for Retest</a>
                </td>
                <td>
                  <form method='post' id='myform'>
                      {% csrf_token %}



                                            <tr><th><label for="id_proof">Proof:</label></th><td><input id="id_proof" maxlength="100" value ="{{ retest.proof.url }}" name="proof" type="text" required /></td></tr>
                      <tr><th><label for="id_name">Name:</label></th><td><input id="id_name" maxlength="100" name="name" value="{{ retest.name }}" type="text" required /></td></tr>
                      <tr><th><label for="id_register_number">Register number:</label></th><td><input id="id_register_number" maxlength="100" value="{{ retest.register_number }}" name="register_number" type="text" required /></td></tr>
                      <tr><th><label for="id_type">Type:</label></th><td><input id="id_type" maxlength="100" name="type" type="text" /></td></tr>
                      <tr><th><label for="id_subject">Subject:</label></th><td><input id="id_subject" maxlength="100" value="{{ retest.subject }}" name="subject" type="text" required /></td></tr>
                      <tr><th><label for="id_test">Test:</label></th><td><input id="id_test" maxlength="100" name="test" value="{{ retest.test }}" type="text" required /></td></tr>


                      <tr>
                        <th><button id="retestbutton" class="btn btn-primary btn-lg" onclick="myFunction()">Accept & Forward</button></th>
                      </tr>

                    <script>
                      function myFunction() {
                        document.getElementById("myForm").submit();
                      }
                    </script>


                  </form>

                </td>
              </tr>

             <!--{% endif %}-->
            {% endfor %}
            {% for internship in internships %}
              <!--{% if user.first_name == internship.Fa_name %}-->
              <tr>
                <td><h4>Internship NOC</h4></td>
                <td>{{ internship.name }}</td>
                <td>{{ internship.register_number }}</td>
                <td>
                  <a href="{{ internship.proof.url }}" class="btn btn-success btn-sm" target='_blank'>Proof for Internship NOC</a>
                </td>
                <td>

                  <form method="post" enctype="multipart/form-data">
                      <button type="button" class="btn btn-primary btn-lg">Accept & Forward</button>
                  </form>

                </td>
              </tr>
              <!--{% endif %}-->
            {% endfor %}
            {% for bonafied in bonafieds %}
              <!--{% if user.first_name == bonafied.Fa_name %}-->
              <tr>
                <td><h4>Bonafied</h4></td>
                <td>{{ bonafied.name }}</td>
                <td>{{ bonafied.register_number }}</td>
                <td>{{ bonafied.purpose }}</td>
                <td>
                  <a href="{{ bonafied.proof.url }}" class="btn btn-success btn-sm" target='_blank'>Proof for Bonafied</a>
                </td>
                <td>
                  <button type="button" class="btn btn-primary btn-lg">Accept & Forward</button>
                </td>
              </tr>
              <!--{% endif %}-->
            {% endfor %}
          </tbody>
      </table>
    </div>
  </div>
{% endblock %}

home/templates/home/generate_pdfs.html
{% extends 'base.html' %}
{% block body %}

      <div class="container">
        <div class="col-md-3"  style="background-color:#2C5F2CAA; border-radius: 15px;">
            <h1>Profile</h1>
            {% if user.userprofile.image %}
            <img src="{{ user.userprofile.image.url }}" width="140">
            {% endif %}
            {% if user.image %}
            <img src="{{ user.image.url }}" width="140">
            {% endif %}
            <br>
            <br>
            <p>Register Number: {{user}}</p>
            <p>First Name: {{user.first_name}}</p>
            <p>Last Name: {{user.last_name}}</p>
            <p>Email: {{user.email}}</p>
        </div>
        <br>
        <div class="col-md-9" style="padding-left:20px">
          {% if request.user.user_type == 1 %}
          <table class='table'>
              <thead>
                <tr>
                  <th>Name:</th>
                  <th>Register Number: </th>
                  <th>Type: </th>
                  <th>Subject: </th>
                  <th>Test: </th>
                  <th>Purpose: </th>
                  <th>proof: </th>
                  <th>Report: </th>
                </tr>
              </thead>
              <tbody>
                {% for j in f %}
                {% if request.user.first_name == j.name %}
                  <tr>
                    <form  method="post" target="_blank">
                      {% csrf_token %}

                            <td><input id="id_name" maxlength="100" name="name" style=" border-radius: 4px; border-style:initial"  value="{{ j.name}}" type="text" required readonly="readonly" /></td>
                            <td><input id="id_register_number" maxlength="100" style=" border-radius: 4px; border-style:initial"  value="{{ j.register_number}}" name="register_number" type="text" required readonly="readonly" /></td>
                            <td><input id="id_type" maxlength="100" value="{{ j.type }}" name="type" style=" border-radius: 4px; border-style:initial"  type="text" readonly="readonly" /></td>
                            <td><input id="id_subject" maxlength="100" value="{{ j.subject }}" style=" border-radius: 4px; border-style:initial"  name="subject" type="text" readonly="readonly"></td>
                            <td><input id="id_test" maxlength="100" name="test"  style=" border-radius: 4px; border-style:initial"  value="{{ j.test }}" type="text"  readonly="readonly"/></td>
                            <td><input id="id_purpose" maxlength="200" style=" border-radius: 4px; border-style:initial"  value="{{ j.purpose }}" name="purpose" type="text" readonly="readonly"/></td>
                            <td><a href="{{ j.proof }}" class="btn btn-success btn-lg" target='_blank'>proof</a></td>

                            <td><button type="submit" id="button" class="btn btn-primary btn-lg" style="background-color:#2C5F2CAA; border-color:#2C5F2CAA;">generate PDF</button></td>

                    </form>

                  </tr>
                  {% endif %}
                  {% endfor %}


                  {% for p in obj %}
                  {% if request.user.first_name == p.name %}
                    <tr>
                      <td>X{{ p.name }}</td>
                      <td>X{{ p.register_number }}</td>
                      <td>X{{ p.type }}</td>
                      <td>X{{ p.subject }}</td>
                      <td>X{{ p.test }}</td>
                      <td>X{{ p.pdf }}</td>
                      <td>X<a href="{{ p.proof }}" class="btn btn-success btn-lg" target='_blank'>proof</a></td>
                      <td>X<a href="{% url 'home:generate_pdfs_actual' %}" class="btn btn-warning btn-lg" target='_blank'> download</a> </td>

                      <td>X<a href="{{ p.pdf }}" class="btn btn-warning btn-lg" target='_blank'> download1</a> </td>
                    </tr>

























                {% endif %}
                {% endfor %}

              </tbody>
          </table>
          {% endif %}
        </div>

{% endblock %}

home/templates/home/onlyforhod.html
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    <title>Base</title>
    {% endblock %}
  </head>
  <body>
    <br>
    <div class="container" >

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid" style="background-color:#FFFFF10" >
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:onlyforhod' %}"><strong>SRMID</strong></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:onlyforhod' %}">Home</a></li>
                    <!--<li> <a href="{% url 'home:retest_list' %}">Requests</a> </li>-->
                    <li> <a href="{% url 'home:onlyforhod' %}"><strong>Final Request</strong></a> </li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_passwords' %}">Change Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="/account/reset-password">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                  <!--<li><a href="{% url 'accounts:student_register' %}">Student Register</a></li>
                  <li><a href="{% url 'accounts:teacher_register' %}">Teacher Register</a></li>-->
                </ul>
                {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

    </div> <!-- /container -->
    {% block body %}

      <div class="container">
        <div class="col-md-3"  style="background-color:#2C5F2CAA; border-radius: 15px;">
            <h1>Profile</h1>
            {% if user.userprofile.image %}
            <img src="{{ user.userprofile.image.url }}" width="140">
            {% endif %}

            {% if user.image %}
            <img src="{{ user.image.url }}" width="140">
            {% endif %}
            <br>
            <br>
            <p>Register Number: {{user}}</p>
            <p>First Name: {{user.first_name}}</p>
            <p> {{user.last_name}}</p>
            <p>Email: {{user.email}}</p>
        </div>
        <br>
        <div class="col-md-9" style="padding-left:50px">
          {% if request.user.user_type == 3 %}
          <table class='table'>
            <thead>
              <tr>
                <th>Type of Request: </th>
                <th> </th>
                <th> </th>
                <th>proof: </th>
                <th> </th>
              </tr>
            </thead>
            <tbody>
               {% for i in a %}

                 <tr>
                   <td> <h2>Request</h2> </td>
                   <td>
                     {% for e in users_all %}
                     {% if e.first_name == i.name %}
                       <img src="{{ e.image.url }}" width="140">
                     {% endif %}
                     {% endfor %}
                   </td>
                   <td></td>
                   <td><a href="{{ i.proof }}" class="btn btn-success btn-lg" target='_blank'>proof</a></td>
                 </tr>
                 <form method='post'>
                     {% csrf_token %}


                      <input id="id_proof" maxlength="100" value="{{ i.proof }}" name="proof" type="hidden" required />
                     <tr><th><label for="id_name">Name:</label></th><td><input id="id_name" maxlength="100" style=" border-radius: 4px; border-style:initial; radius: 4px;" name="name" value="{{ i.name }}" type="text" required /></td></tr>
                     <tr><th><label for="id_register_number">Register number:</label></th><td><input id="id_register_number" style=" border-radius: 4px; border-style:initial" maxlength="100" value="{{ i.register_number }}" name="register_number" type="text" required /></td></tr>

                     {% if i.type %}
                     <tr><th><label for="id_type">Type:</label></th><td><input id="id_type" maxlength="100" name="type" style=" border-radius: 4px; border-style:initial" value="{{ i.type }}" type="text" /></td></tr>
                     {% endif %}

                     {% if i.test and i.subject %}
                     <tr><th><label for="id_subject">Subject:</label></th><td><input id="id_subject" maxlength="100" style=" border-radius: 4px; border-style:initial" name="subject" value="{{ i.subject }}" type="text" /></td></tr>
                     <tr><th><label for="id_test">Test:</label></th><td><input id="id_test" maxlength="100" name="test" style=" border-radius: 4px; border-style:initial" value="{{ i.test }}" type="text" /></td></tr>
                     {% endif %}

                     {% if i.purpose %}
                     <tr><th><label for="id_purpose">Purpose:</label></th><td><input id="id_purpose" maxlength="200" style=" border-radius: 4px; border-style:initial" value="{{ i.purpose }}" name="purpose" type="text" /></td></tr>
                     {% endif %}


                     <tr>
                       <th><button id="mybutton" onclick="myFunction()" class="btn btn-danger btn-lg" type='submit'>Verify</button></th>
                     </tr>
                     <script type="text/javascript">
                       function myFunction(){
                         document.getElementById("mybutton").innerHTML
                       }
                     </script>
                 </form>
               {% endfor %}

             </tbody>
          </table>
          {% endif %}
        </div>

    {% endblock %}

  </body>
  <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

home/templates/home/upload_bonafied_form.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}

{% load static %}


<div class="container">
  <div class="container">
    <br>
    <div class="col-md-3"  style="background-color:#2C5F2CAA; border-radius: 15px;">
      <h1>Profile</h1>
      {% if user.userprofile.image %}
      <img src="{{ user.userprofile.image.url }}" width="140">
      {% endif %}
      {% if user.image %}
      <img src="{{ user.image.url }}" width="140">
      {% endif %}
      <br>
      <br>
      <p>Register Number: {{user}}</p>
      <p>First Name: {{user.first_name}}</p>
      <p>Department: {{user.department}}</p>
      <p>Email: {{user.email}}</p>
    </div>

    <h2>&nbsp&nbsp&nbsp&nbsp&nbsp Apply for Bonafied </h2><br>
    <div class="col-md-5" style="padding-left:50px">
        <form method='post' enctype="multipart/form-data">

          <img src="srmlogo.jpg" alt="">

          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" name="button" class='btn btn-success'>Submit</button>
        </form>
    </div>
  </div>

</div>
{% endblock %}

home/templates/home/upload_internship_form.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
  <div class="container">
    <br>
    <div class="col-md-3"  style="background-color:#2C5F2CAA; border-radius: 15px;">
        <h1>Profile</h1>
        {% if user.userprofile.image %}
        <img src="{{ user.userprofile.image.url }}" width="140">
        {% endif %}
        {% if user.userprofile.image %}
        <img src="{{ user.image.url }}" width="140">
        {% endif %}
        <br>
        <br>
        <p>Register Number: {{user}}</p>
        <p>First Name: {{user.first_name}}</p>
        <p>Last Name: {{user.last_name}}</p>
        <p>Email: {{user.email}}</p>
    </div>
    <h2>&nbsp&nbsp&nbsp&nbsp&nbsp Apply for Internship NOC </h2><br>
    <div class="col-md-5" style="padding-left:50px">
        <form method='post' enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" name="button" class='btn btn-success'>Submit</button>
        </form>
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/upload_retest_form.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
  <div class="container">
    <br>

    <div class="col-md-3" style="background-color:#2C5F2CAA; border-radius: 15px;">
      <h1>Profile</h1>
      {% if user.userprofile.image %}
      <img src="{{ user.userprofile.image.url }}" width="140">
      {% endif %}
      {% if user.image %}
      <img src="{{ user.image.url }}" width="140">
      {% endif %}
      <br>
      <br>
      <p>Register Number: {{user}}</p>
      <p>First Name: {{user.first_name}}</p>
      <p>Department: {{user.department}}</p>
      <p>Email: {{user.email}}</p>
    </div>
    <h2>&nbsp&nbsp&nbsp&nbsp&nbsp Apply for Retest</h2><br>
    <div class="col-md-5" style="padding-left:50px">
        <form method='post' enctype="multipart/form-data">
          {% csrf_token %}

                  {{ form|crispy }}
                  <button type="submit" name="button" class='btn btn-success'>Submit</button>
        </form>
    </div>
  </div>
</div>
{% endblock %}