IDservice/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from IDservice import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import  url
from accounts import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns=[
    url(r'^login/$', login, { 'template_name': 'accounts/login.html' }, name='login'),
    url(r'^logout/$', logout, { 'template_name': 'accounts/logout.html'}, name='logout'),
    ##url(r'^register/$', views.register, name='register'),  ##uncomment it to get back to old.
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^change-password$', views.change_password, name='change_passwords'),

    url(r'^reset-password/$', password_reset, { 'template_name': 'accounts/reset_password.html', 'post_reset_redirect':'accounts:password_reset_done',
    'email_template_name':'accounts/reset_password_email.html' }, name='reset_password'),

    url(r'^reset_password/done$', password_reset_done, {'template_name':'accounts/reset-password_reset_done'}, name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name':'accounts/reset-password_reset_confirm.html',
        'post_reset_redirect':'password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete, {'template_name':'accounts/reset-password_reset_complete.html'}, name='password_reset_complete'),

    url(r'^password/$', views.change_password),

    ##
    url(r'^register/$', views.SignUpView.as_view(), name='register'),
    url(r'^register/student/$', views.register, name='student_register'),
    url(r'^register/teacher/$', views.Teacherregister, name='teacher_register'),
    url(r'^register/HOD/$', views.hodregister, name='hod_register'),
    ## remove all if you want to go back to old
]

home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views

urlpatterns=[
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_students, name='change_students'),
    url(r'^send_mail_to_fa$', views.send_mail_to_fa, name='send_mail_to_fa'),           ##remove to get the old back.
    url(r'^bonafied-certificate$', views.upload_bonafied_form, name='upload_bonafied_form'),
    url(r'^Internship$', views.Internship, name='Internship'),
    url(r'^Internship/upload$', views.upload_internship_form, name='upload_internship_form'),
    url(r'^onlyforhod$', views.onlyforhod_view, name='onlyforhod'),
    #url(r'^Retest$', views.Retest, name='Retest'),
    url(r'^Retest/upload$', views.upload_retest_form, name='upload_retest_form'),
    url(r'^Retest/retest_list$', views.retest_list, name='retest_list'),
    url(r'^Retest/accepted_students_list$', views.accepted_students_view, name='accepted_students'),
    url(r'^genetate_pdfs$', views.generate_pdfs_view, name='generate_pdfs'),
    url(r'^genetate_pdfs_actual$', views.generate_pdfs_actual, name='generate_pdfs_actual'),
    #url(r'^genetate_obj_pdf$', views.generate_obj_pdf, name='generate_obj_pdf')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser #add user to get back to old.
from django.db.models.signals import post_save
# Create your models here.
##remove it to get back to old
FA_CHOICES=[
    ('Rajasekaran', 'Rajasekaran'),
    ('Senthil Kumar', 'Senthil Kumar'),
    ("B. Sowmiya", "B. Sowmiya")
]
class User(AbstractUser):
 USER_TYPE_CHOICES = (
      (1, 'student'),
      (2, 'faculty advisor'),
      (3, 'head of the department'),
      (4, 'admin'),
  )

 user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, null=True)
 facultyadvisor = models.CharField(max_length=100,  choices=FA_CHOICES, null=True)
 department = models.CharField(max_length=100, null=True)
 #
 image=models.ImageField(upload_to='profile_image', blank=True, null=True)
 #
##




class Students(models.Model):
    user=models.OneToOneField(User, on_delete=models.PROTECT)
    ID_number=models.CharField(default='', max_length=100)
    Description=models.CharField(default='', max_length=100)
    phone=models.IntegerField(default=0)
    image=models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile=Userprofile.objects.create(user=kwargs['instance'])

#post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
import re
#from django.contrib.auth.models import User     uncomment to get the old back
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import User  #remove to get the old back
from django.db import transaction       #remove to get the old back

#fa = User.objects.filter(user_type=1)
fa = User.objects.filter(user_type=2)

class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)
    username = forms.RegexField(regex=re.compile(r'^RA[0-9]{13}$'), required=True)  #make it reagex field, change it's name to id number and give your regex
    first_name=forms.CharField(required=True)
    department=forms.CharField(required=True)   ##remove to get the old back
    #last_name=forms.CharField(required=True)
    #u2 = u['user_type'== 2 ]
    #facultyadvisor = forms.ModelChoiceField(queryset=fa, empty_label=None)     #field1 = forms.ModelChoiceField(queryset=User.objects.get(user_type=2))
    #fa_name = forms.ForeignKey(User)

    class Meta(UserCreationForm.Meta):
        model=User
        fields=[
            'image',
            'username',

            #'last_name',
            'email',
            'department',
            'facultyadvisor',
            'password1',
            'password2'
        ]

    @transaction.atomic                            ##remove to get the old back
    def save(self, commit=True):
        user=super(RegistrationForm, self).save(commit=False)
        #user.is_student = True
        user.user_type=1                                 ##remove to get the old one back
        user.first_name=self.cleaned_data['first_name']
        #user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']
        user.department = self.cleaned_data['department']
        user.facultyadvisor = self.cleaned_data['facultyadvisor']

        if commit:
            user.save()
        return user

## remove to get the old
##Teacher registeration form

class TeacherRegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)
    username = forms.RegexField(regex=re.compile(r'^10[0-9]{4}$'), required=True)  #make it reagex field, change it's name to id number and give your regex
    first_name=forms.CharField(required=True)
    department=forms.CharField(required=True)
    #last_name=forms.CharField(required=True)
    #facultyadvisor=forms.CharField(required=False)

    class Meta(UserCreationForm.Meta):
        model=User
        fields=[
            'image',
            'username',

            #'last_name',
            'email',
            'department',
            #'facultyadvisor',
            'password1',
            'password2'
        ]

    @transaction.atomic                            ##remove to get the old back
    def save(self, commit=True):
        user=super(TeacherRegistrationForm, self).save(commit=False)
        #user.is_teacher = True
        user.user_type=2                                   ##remove to get the old one back
        user.first_name=self.cleaned_data['first_name']
        #user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']
        user.department = self.cleaned_data['department']
        #user.facultyadvisor = self.cleaned_data['facultyadvisor']

        if commit:
            user.save()
        return user
##



##
class HODRegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)
    username = forms.RegexField(regex=re.compile(r'^100[0-9]{3}$'), required=True)  #make it reagex field, change it's name to id number and give your regex
    first_name=forms.CharField(required=True)
    #last_name=forms.CharField(required=True)
    department=forms.CharField(required=True)
    #facultyadvisor=forms.CharField(required=False)
    class Meta(UserCreationForm.Meta):
        model=User
        fields=[
            'image',
            'username',
            'first_name',
            #'last_name',
            'email',
            'department',
            #'facultyadvisor',
            'password1',
            'password2'
        ]

    @transaction.atomic                            ##remove to get the old back
    def save(self, commit=True):
        user=super(HODRegistrationForm, self).save(commit=False)
        #user.is_teacher = True
        user.user_type=3                                       ##remove to get the old one back
        user.first_name=self.cleaned_data['first_name']
        #user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']
        user.department = self.cleaned_data['department']
        #user.facultyadvisor = self.cleaned_data['facultyadvisor']

        if commit:
            user.save()
        return user
##


        ##
    ## @transaction.atomic
    ##def save(self):
    ##    user = super().save(commit=False)
    ##    user.is_student = True
    ##    user.save()
    ##    student = Student.objects.create(user=user)
    ##    student.interests.add(*self.cleaned_data.get('interests'))
    ##    return user
        ##






class EditProfileForm(UserChangeForm):
    class Meta:
        model=User
        fields=[
            'image',
            'first_name',
            'password',
            'email',
        ]

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, TemplateView

from accounts.forms import (
    RegistrationForm,
    TeacherRegistrationForm,
    HODRegistrationForm,
    EditProfileForm
)

#from django.contrib.auth.models import User     uncomment to get the old back
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from accounts.models import User

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('home:home'))
    else:
        form = RegistrationForm()

    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)



##remove to get back the old.

def Teacherregister(request):
    if request.method =='POST':
        form = TeacherRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('home:home'))
    else:
        form = TeacherRegistrationForm()

    args = {'form': form}
    return render(request, 'accounts/teacherreg_form.html', args)
##



##
def hodregister(request):
    if request.method =='POST':
        form = HODRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('home:home'))
    else:
        form = HODRegistrationForm()

    args = {'form': form}
    return render(request, 'accounts/hodreg_form.html', args)
##


##
class SignUpView(TemplateView):
    template_name = 'accounts/signup.html'
##


##remove to get the old back
#class StudentSignUpView(CreateView):
    #model = User
    #form_class = RegistrationForm
    #template_name = 'registration/signup_form.html'

    #def get_context_data(self, **kwargs):
    #    kwargs['user_type'] = 'student'
    #    return super().get_context_data(**kwargs)

    #def form_valid(self, form):
    #    user = form.save()
    #    login(self.request, user)
    #    return redirect('students:quiz_list')
##


##remove to get the old back
#class TeacherSignUpView(CreateView):
    #model = User
    #form_class = TeacherRegistrationForm
    #template_name = 'registration/signup_form.html'

    #def get_context_data(self, **kwargs):
    #    kwargs['user_type'] = 'teacher'
    #    return super().get_context_data(**kwargs)

    #def form_valid(self, form):
    #    user = form.save()
    #    login(self.request, user)
    #    return redirect('teachers:quiz_change_list')
##




def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            #return redirect(reverse('accounts:view_profile'))
            return redirect(reverse('home:home'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_passwords'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    <h1>Home</h1>
    {% block head %}
    <title>Home</title>
    {% endblock %}
  {% block body %}
    <div class="container" align=center style="width:500px">
       <form method="post">
         {% csrf_token %}
         {{ form|crispy }}
         <button type="submit">Submit</button>
       </form>
    </div>
    {% endblock%}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    <h1>Home</h1>
    {% block head %}
    <title>Home</title>
    {% endblock %}
  {% block body %}
    <div class="container" align=center style="width:500px">
       <form method="post"  enctype="multipart/form-data">
         {% csrf_token %}
         {{ form|crispy }}
         <button type="submit">Submit</button>
       </form>
    </div>
    {% endblock%}

accounts/templates/accounts/hodreg_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container" align=center style="width:500px">
  <h1>HOD Register</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form|crispy}}
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html'%}
{% block body %}
{% load crispy_forms_tags %}
<div class="container" align= center style="background-color: #2C5F2CA4; width:500px; height:380px;  border-radius: 25px; border: solid black">
  <div align=center class="login_box_well" style="width:400px;">
        <h1>Welcome!</h1>
        <p>You can log in here!</p>
        <h2>Login</h2>
        <form method="post">
          {% csrf_token %}
          {{ form|crispy}}
          <button type="submit" class="btn btn-success btn-lg" style="background-color: #2C5F2AAA">Login</button>
        </form>
    </div>

</div>

  {% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html'%}
{% block body %}
  <div class="container" align=center>
        <h1>Logged out</h1>
        <p>You have logged out!</p>
  </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
    <h1>Home</h1>
    {% block head %}
    <title>Home</title>
    {% endblock %}
  {% block body %}
    <div class="container">
      <h1>Profile</h1>
      {% if user.userprofile.image %}
      <img src="{{ user.userprofile.image.url }}" width="140">
      {% endif %}
      <br><br>
      <p>Register Number: {{user}}</p>
      <p>First Name: {{user.first_name}}</p>
      <p>Last Name: {{user.last_name}}</p>
      <p>Email: {{user.email}}</p>
      <!--<p>Description: {{user.Userprofile.Description}}</p>-->   <!--uncomment this and below this to get the old back--> 
      <!--<p>Phone: {{user.userprofile.phone}}</p>-->
    </div>
    {% endblock%}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container" align=center style="width:500px">
  <h1>Student Register</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form|crispy}}
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html'%}
{% block body %}
{% load crispy_forms_tags %}
  <div class="container" align=center style="width:500px">
        <h1>Password Reset</h1>
        <p>
          Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
        </p>
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-success">Reset Password</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html'%}
{% block body %}
  <div class="container" align=center>
        <h1>Password Reset complete</h1>
        <p>
          Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
        </p>
        <a href="{% url'accounts:login' %}"></a>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html'%}
{% block body %}
  <div class="container" align=center>
        <h1>Password Reset</h1>
        <p>.
        </p>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p}}
          <button type="submit">Reset Password</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html'%}
{% block body %}
  <div class="container" align=center>
        <h1>Password Reset</h1>
        <p>
          Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
        </p>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block body %}
<div class="container" align=center>
    <h2>Sign up for an account</h2>
    <p class="lead">Select below the type of account you want to create</p>
    <a href="{% url 'accounts:student_register' %}" class="btn btn-success" role="button"> Student </a>
    <a href="{% url 'accounts:teacher_register' %}" class="btn btn-success" role="button"> Faculty advisor</a>
    <a href="{% url 'accounts:hod_register' %}" class="btn btn-success" role="button"> HOD</a>
</div>
{% endblock %}

accounts/templates/accounts/teacherreg_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container" align=center style="width:500px">
  <h1>Teacher Register</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form|crispy}}
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}